name: Static code analysis

on: [pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run PHPStan
        uses: docker://jakzal/phpqa:php7.3-alpine
        with:
          args: phpstan analyze

  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run PHP-CS-Fixer
        uses: docker://jakzal/phpqa:php7.3-alpine
        with:
            args: php-cs-fixer fix --dry-run -vvv

  roave-bc-check:
    name: Roave BC Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Roave BC Check
        uses: docker://nyholm/roave-bc-check-ga
